const technicalData = {
  electromecanica: {
    titulo: 'Electromecánica',
    perfil: [
      'Proyectar y montar equipos componentes e instalaciones mecánicas, electromecánicas, de sistemas neumáticos, oleo hidráulicos; circuitos eléctricos y de control de automatismos; herramientas y dispositivos',
      'Realizar ensayos de materiales y ensayos eléctricos, mecánicos, electromecánicos',
      'Operar equipos e instalaciones y dispositivos de accionamiento y control de la producción  y máquinas herramientas',
      'Realizar los mantenimientos, predictivo, preventivo, funcional operativo y correctivo de componentes, equipos e instalaciones electromecánicas',
      'Instalar líneas de consumo y distribución de energía eléctrica de baja y media tensión',
    ],
    areaOcupacional: [
      'Industria en general',
      'Empresas de generación, transporte y distribución de energía',
      'Empresas de servicios de montaje y mantenimiento',
      'Laboratorios de Ensayos de Materiales',
      'Talleres de mantenimiento electromecánico',
      'Sectores de control, suministros,  diseño asistido por computadora',
      'Profesional independiente',
    ],
    espacioCurricular: {
      'Tercer año': [
        'Conocimiento de los Materiales',
        'Representación Gráfica e Interpretación de Planos I',
        'Taller Sección Electricidad',
        'Taller Sección Mecánica',
      ],
      'Cuarto año': [
        'Representación Gráfica e Interpretación de Planos II',
        'Laboratorio de Ensayos de Materiales',
        'Mecánica Técnica',
        'Introducción a los Circuitos Eléctricos',
        'Gestión y Comercialización',
        'Taller Sección Electricidad',
        'Taller Sección Mecánica',
      ],
      'Quinto año': [
        'Termodinámica y Máquinas Térmicas',
        'Electrónica',
        'Elementos de Transporte y Transmisión Mecánica',
        'Máquinas y Comandos Eléctricos',
        'Organización Industrial',
        'Procesos de Fabricación Industrial',
        'Taller Automatización',
        'Taller Automatización',
      ],
      'Sexto año': [
        'Instalaciones Eléctricas',
        'Proyecto y Diseño de Equipos Electromecánicos',
        'Sistemas de Control y Automatización Industrial',
        'Mantenimiento y Ensayos de Equipos Electromecánicos',
        'Economía',
        'Marco Jurídico',
        'Taller CNC',
        'Taller Montaje',
        'Prácticas Profesionalizantes – Pasantía',
      ],
    },
  },
  electronica: {
    titulo: 'Electrónica',
    perfil: [
      'Proyectar componentes y equipos de electrónica analógica y/o digital, con tecnología electrónica estándar y de baja o mediana complejidad Realizar ensayos y mediciones eléctricas y electrónicas en dispositivos, componentes, equipos e instalaciones con electrónica analógica y/o digital, estándar de baja o mediana complejidad',
      'Operar componentes, productos y equipos con electrónica analógica y/o digital',
      'Realizar los mantenimientos predictivo, preventivo, funcional operativo, y correctivo de componentes, productos y equipos con electrónica analógica y/o digital, estándar de baja o mediana complejidad',
      'Montar e instalar productos, dispositivos y componentes electrónicos (electrónica industrial, equipos de Radio Frecuencia, equipos de soporte para telecomunicaciones, sistemas electrónicos para informática y microinformática)',
      'Instalar productos y equipos',
      'Realizar la selección, asesoramiento y comercialización de dispositivos, componentes, productos y equipos Generar emprendimientos',
    ],
    areaOcupacional: [
      'Industria electrónica en general',
      'Distintas fases de los procesos productivos de otras industrias',
      'Empresas de telecomunicaciones, radio, televisión y multimedios',
      'Empresas de generación, transporte y distribución de energía eléctrica',
      'Laboratorios electrónicos de  mantenimiento y reparación',
      'Infraestructura urbana y edificios',
      'Profesional independiente',
    ],
    espacioCurricular: {
      'Tercer año': [
        'Componentes eléctricos – electrónicos y su tecnología',
        'Dibujo y Diseño eléctrico – electrónico',
        'Instrumentos y Herramientas de propósito general',
        'Taller',
      ],
      'Cuarto año': [
        'Introducción a la Tecnología Digital',
        'Laboratorio de Ensayos y Mediciones',
        'Electrónica',
        'Circuitos y Redes I',
        'Taller',
      ],
      'Quinto año': [
        'Organización, Gestión, Comercialización de los Emprendimientos Productivos',
        'Introducción al Control',
        'Telecomunicaciones',
        'Laboratorio de Ensayos y Mediciones II',
        'Circuitos y Redes II',
        'Circuitos y Dispositivos Analógicos',
        'Taller',
      ],
      'Sexto año': [
        'Marco Jurídico de los Procesos Productivos',
        'Economía',
        'Ambientes, Seguridad e Higiene',
        'Sistemas de Telecomunicaciones',
        'Sistemas Industriales',
        'Sistemas de Desarrollo',
        'Máquinas Eléctricas',
        'Proyecto y Diseño Electrónico',
        'Prácticas Profesionalizantes – Pasantía',
      ],
    },
  },
  'energias-renovables': {
    titulo: 'Energías Renovables',
    perfil: [
      'Proyectar y diseñar equipos de energías renovables',
      'Montar e instalar componentes, equipos e instalaciones de energías renovables',
      'Controlar y participar en el suministro de los servicios auxiliares',
      'Operar y mantener equipos e instalaciones de energías renovables',
      'Realizar e interpretar ensayos de materiales para energías renovables',
      'Comercializar, seleccionar, asesorar y generar y/o participar en emprendimientos vinculados con áreas de su profesionalidad',
    ],
    areaOcupacional: [
      'Industria',
      'Empresas de generación, transporte y distribución de energía',
      'Empresas de telecomunicaciones',
      'Empresas de construcción',
      'Estudios de arquitectura',
      'Consultoras energéticas',
      'Consultoras ambientales',
      'Cooperativas eléctricas',
      'Establecimientos agropecuarios',
      'Profesional independiente',
    ],
    espacioCurricular: {
      'Tercer año': [
        'Estudio de los Recursos Energéticos',
        'Representación Gráfica e Interpretación de Planos I',
        'Taller Sección Electricidad',
        'Taller Sección Energía Solar Térmica',
      ],
      'Cuarto año': [
        'Representación Gráfica e Interpretación de Planos II',
        'Evaluación de los Recursos Energéticos',
        'Mecánica Técnica y Transmisión de Movimiento',
        'Materiales y  sus Propiedades',
        'Introducción a los Circuitos Eléctricos',
        'Taller Sección Electricidad',
        'Taller Sección Electrónica',
      ],
      'Quinto año': [
        'Termodinámica de los Procesos de Energías Renovables',
        'Radicaciones Electromagnéticas',
        'Electrónica',
        'Máquinas y Comandos Eléctricos',
        'Taller Mini-Hidráulica',
        'Taller Eólico',
        'Taller Biomasa',
      ],
      'Sexto año': [
        'Instalaciones Eléctricas',
        'Proyecto y Diseño de Equipos de Instalaciones de Energías Renovables',
        'Proyectos Comunitarios de Energías Renovables',
        'Mantenimiento y Reparación de Equipos de Energías Renovables',
        'Taller Montaje de Equipos de Energía Renovable',
        'Taller Eficiencia Energética y Arquitectura Bioclimática',
        'Prácticas Profesionalizantes – Pasantía',
      ],
    },
  },
}

export default function getData() {
  return new Promise((resolve, reject) =>
    setTimeout(() => resolve(technicalData), 0)
  )
}
